version: '3.9'
services:
  qdrant:
    shm_size: '1g'
    ulimits:
      memlock: -1
      stack: 67108864
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
    image: qdrant/qdrant:latest
